### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by riccardobl** [riccardobl/JMELink-SP#1]
- [ ] Implement Alpha blending/Alpha testing/Alpha dithering
- [ ] Fix errors when sp gets closed
- [x] Use the same substance among shared materials. 
- [x] Allow to set queue bucket from substances def
- [ ] it doesn't work properly with instancing
